### ISSUE TITLE
undefined method `capitalize' for nil:NilClass

### ISSUE THREAD

**Issue by bobweston** [railsware/caphub#13]
I'm trying to deploy an application using caphub and I'm seeing the following error when trying to run deploy:setup

/lib/caphub/app.rb:84:in `mk_shell': undefined method`capitalize' for nil:NilClass (NoMethodError)
    from ./lib/caphub/app.rb:34:in `initialize'
    from recipes/db.rb:9:in`new'
    from recipes/db.rb:9:in `block (2 levels) in load'

Anyone have any thoughts they could share on what might be causing this?

**Comment by le0pard** [comment]
This is not caphub. Gem doesn't have "/lib/caphub/app.rb"
